name: cached_query
repository: https://github.com/D-James-GH/cached_query

packages:
  - packages/**
  - examples/**

ide:
  intellij: false


command:
  bootstrap:
    dev_dependencies:
      mockito: ^5.4.5
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"
  version:
    linkToCommits: true
    workspaceChangelog: true

scripts:
  build:devtools:
    run: cd packages/devtools_extension && dart run devtools_extensions build_and_copy --source=. --dest=../cached_query/extension/devtools
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
  analyze:
    run: |
      melos exec -c 10 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.
    packageFilters:
      noPrivate: true
  get:
    run: melos exec flutter pub get
    description: Run `flutter pub get` for all packages.
  format:check:
    run: melos exec dart format . --output=none --set-exit-if-changed
    description: Run `dart format` for all packages.
    packageFilters:
      noPrivate: true
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  get:examples: "find ./examples/ -maxdepth 1 -mindepth 1 -type d -exec flutter pub get {} \\;"
  gen:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner
    description: Build all generated files for Flutter packages in this project.
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
      ignore:
        - "examples/**"
