// Mocks generated by Mockito 5.2.0 from annotations
// in cached_query/test/infinite_query_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:cached_query/src/storage_interface.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [StorageInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageInterface extends _i1.Mock implements _i2.StorageInterface {
  MockStorageInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FutureOr<dynamic> get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key]))
          as _i3.FutureOr<dynamic>);
  @override
  void delete(String? key) =>
      super.noSuchMethod(Invocation.method(#delete, [key]),
          returnValueForMissingStub: null);
  @override
  void put<T>(String? key, {T? item}) =>
      super.noSuchMethod(Invocation.method(#put, [key], {#item: item}),
          returnValueForMissingStub: null);
  @override
  void deleteAll() => super.noSuchMethod(Invocation.method(#deleteAll, []),
      returnValueForMissingStub: null);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
