name: full
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  meta: ^1.9.1
  connectivity_plus: ^7.0.0
  shared_models:
    path: ../shared_models
  cached_query_flutter: ^3.4.0-dev.0
  cached_storage: ^3.3.0-dev.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
