include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
    strict-inference: true

linter:
  rules:
    always_declare_return_types: true
    prefer_final_locals: true
    require_trailing_commas: true
