include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    avoid_print: info
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    cancel_subscriptions: true
    avoid_print: true
    package_api_docs: true
    unnecessary_statements: true
    sort_child_properties_last: true
    always_declare_return_types: true
    unnecessary_lambdas: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    join_return_with_assignment: true
    no_leading_underscores_for_local_identifiers: true
    prefer_final_in_for_each: true
    public_member_api_docs: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    sized_box_shrink_expand: true
    unnecessary_await_in_return: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    require_trailing_commas: true

    # possibly good ones
    flutter_style_todos: true

#    overridden_fields: true
